### ISSUE TITLE
Copying files broken by Node v8.5.0 

### ISSUE THREAD

**Issue by arwhyte** [krampstudio/grunt-jsdoc#179]
Since Node v8.5.0 `fs.copyFile` and `fs.copyFileSync` require the full path of the destination file, breaking the jsdoc build process since`lib/jsdoc/fs.js` (until jsdoc 3.5.5.) prefers native methods over its overrides.  See error encountered below.

The jsdoc team has resolved the issue with the release of jsdoc 3.5.5.  Please update grunt-jsdoc accordingly.

npm list jsdoc
caliperjs@1.1.0 /Users/arwhyte/Development/repos/github/IMSGlobal/caliper-js
└─┬ grunt-jsdoc@2.1.1
  └── jsdoc@3.4.3

**Issue first reported**
https://github.com/jsdoc3/jsdoc/issues/1438

**Issue resolved**
https://github.com/jsdoc3/jsdoc/pull/1440

**jsdoc release (3.5.5.)**
https://github.com/jsdoc3/jsdoc/releases/tag/3.5.5

**Local error encountered (running node v8.6.0)**

```
Running "jsdoc:dist" (jsdoc) task
>> fs.js:1919
>>   binding.copyFile(src, dest, flags);
>>           ^
>>
>> Error: EISDIR: illegal operation on a directory, copyfile '/Users/arwhyte/Development/repos/github/IMSGlobal/caliper-js/node_modules/jsdoc/templates/default/static/fonts/OpenSans-Bold-webfont.eot' -> 'doc/fonts'
>>     at Object.fs.copyFileSync (fs.js:1919:11)
>>     at /Users/arwhyte/Development/repos/github/IMSGlobal/caliper-js/node_modules/jsdoc/templates/default/publish.js:471:12
>>     at Array.forEach (<anonymous>)
>>     at Object.exports.publish (/Users/arwhyte/Development/repos/github/IMSGlobal/caliper-js/node_modules/jsdoc/templates/default/publish.js:468:17)
>>     at Object.module.exports.cli.generateDocs (/Users/arwhyte/Development/repos/github/IMSGlobal/caliper-js/node_modules/jsdoc/cli.js:430:39)
>>     at Object.module.exports.cli.processParseResults (/Users/arwhyte/Development/repos/github/IMSGlobal/caliper-js/node_modules/jsdoc/cli.js:383:20)
>>     at module.exports.cli.main (/Users/arwhyte/Development/repos/github/IMSGlobal/caliper-js/node_modules/jsdoc/cli.js:227:14)
>>     at Object.module.exports.cli.runCommand (/Users/arwhyte/Development/repos/github/IMSGlobal/caliper-js/node_modules/jsdoc/cli.js:180:5)
>>     at /Users/arwhyte/Development/repos/github/IMSGlobal/caliper-js/node_modules/jsdoc/jsdoc.js:103:9
>>     at Object.<anonymous> (/Users/arwhyte/Development/repos/github/IMSGlobal/caliper-js/node_modules/jsdoc/jsdoc.js:104:3)
>>     at Module._compile (module.js:624:30)
>>     at Object.Module._extensions..js (module.js:635:10)
>>     at Module.load (module.js:545:32)
>>     at tryModuleLoad (module.js:508:12)
>>     at Function.Module._load (module.js:500:3)
>>     at Function.Module.runMain (module.js:665:10)
```

**Comment by krampstudio** [comment]
Version `2.2.0` should fix the issue. Thanks for reporting.

**Comment by arwhyte** [comment]
Thanks for your quick response.  Cheers.
