### ISSUE TITLE
Upgrade to jsdoc 3.5.5

### ISSUE THREAD

**Issue by sovknaf** [krampstudio/grunt-jsdoc#180]
Fixes a jsdoc issue in node 8.5+ that occurs when running npm install in redux-orm.

jsdoc3/jsdoc#1438

The exception stack looks like the below:

```
Running "jsdoc:dist" (jsdoc) task
>> fs.js:1919
>>   binding.copyFile(src, dest, flags);
>>           ^
>>
>> Error: EISDIR: illegal operation on a directory, copyfile '/Users/michael.knaf/Documents/Projects/ewe-jahresfeedback/product-jahresfeedback-ewe/node_modules/jsdoc/templates/default/static/fonts/OpenSans-Bold-webfont.eot' -> 'doc/fonts'
>>     at Object.fs.copyFileSync (fs.js:1919:11)
>>     at /Users/michael.knaf/Documents/Projects/ewe-jahresfeedback/product-jahresfeedback-ewe/node_modules/jsdoc/templates/default/publish.js:471:12
>>     at Array.forEach (<anonymous>)
>>     at Object.exports.publish (/Users/michael.knaf/Documents/Projects/ewe-jahresfeedback/product-jahresfeedback-ewe/node_modules/jsdoc/templates/default/publish.js:468:17)
>>     at Object.module.exports.cli.generateDocs (/Users/michael.knaf/Documents/Projects/ewe-jahresfeedback/product-jahresfeedback-ewe/node_modules/jsdoc/cli.js:430:39)
>>     at Object.module.exports.cli.processParseResults (/Users/michael.knaf/Documents/Projects/ewe-jahresfeedback/product-jahresfeedback-ewe/node_modules/jsdoc/cli.js:383:20)
>>     at module.exports.cli.main (/Users/michael.knaf/Documents/Projects/ewe-jahresfeedback/product-jahresfeedback-ewe/node_modules/jsdoc/cli.js:227:14)
>>     at Object.module.exports.cli.runCommand (/Users/michael.knaf/Documents/Projects/ewe-jahresfeedback/product-jahresfeedback-ewe/node_modules/jsdoc/cli.js:180:5)
>>     at /Users/michael.knaf/Documents/Projects/ewe-jahresfeedback/product-jahresfeedback-ewe/node_modules/jsdoc/jsdoc.js:103:9
>>     at Object.<anonymous> (/Users/michael.knaf/Documents/Projects/ewe-jahresfeedback/product-jahresfeedback-ewe/node_modules/jsdoc/jsdoc.js:104:3)
>>     at Module._compile (module.js:624:30)
>>     at Object.Module._extensions..js (module.js:635:10)
>>     at Module.load (module.js:545:32)
>>     at tryModuleLoad (module.js:508:12)
>>     at Function.Module._load (module.js:500:3)
>>     at Function.Module.runMain (module.js:665:10)
Warning: jsdoc terminated with a non-zero exit code Use --force to continue.

Aborted due to warnings.
```

**Comment by apricot13** [comment]
We're encountering this issue as well.

**Comment by krampstudio** [comment]
`grunt-jsdoc` is already using [jsdoc 3.5.5](https://github.com/krampstudio/grunt-jsdoc/blob/master/package.json#L44). 
Last tests are passing on node 8.5.0 : https://travis-ci.org/krampstudio/grunt-jsdoc/jobs/282268122

Maybe you're not using the last version.

**Comment by krampstudio** [comment]
Please reopen if needed
